"""Deploys backend/*.ts to Val Town as one HTTP val and saves its URL to .backend_url.

- backend/dashboard.html is the ops console; it is embedded into ui.ts at deploy time.
- Secrets go to the val's environment variables, never into code:
  BLAND_API_KEY, ADMIN_TOKEN (generated once, saved to .env), PATHWAY_ID, and optionally
  TRANSFER_NUMBER (scheduler warm-transfer line) and BLAND_WEBHOOK_SECRET (webhook signing).
"""
import json, pathlib, secrets, urllib.request, urllib.error, urllib.parse
ROOT = pathlib.Path(__file__).parent.parent
BACKEND = ROOT / "backend"
ENV_FILE = ROOT / ".env"
NAME = "pennScheduling"


def env():
    return dict(l.split("=", 1) for l in ENV_FILE.read_text().splitlines() if "=" in l and not l.startswith("#"))


E = env()
if "ADMIN_TOKEN" not in E:
    tok = secrets.token_urlsafe(24)
    with ENV_FILE.open("a") as f:
        f.write(("" if ENV_FILE.read_text().endswith("\n") else "\n") + f"ADMIN_TOKEN={tok}\n")
    E["ADMIN_TOKEN"] = tok
    print("generated ADMIN_TOKEN (saved to .env)")
TOKEN = E["VALTOWN_TOKEN"].strip()


def call(method, path, body=None):
    req = urllib.request.Request("https://api.val.town" + path, method=method,
        data=json.dumps(body).encode() if body is not None else None,
        headers={"Authorization": f"Bearer {TOKEN}", "content-type": "application/json"})
    try:
        with urllib.request.urlopen(req) as r:
            t = r.read(); return json.loads(t) if t else {}
    except urllib.error.HTTPError as e:
        return {"_error": e.code, "_body": e.read().decode()[:600]}


me = call("GET", "/v1/me")
val = call("GET", f"/v2/alias/vals/{me['username']}/{NAME}")
if "_error" in val:
    val = call("POST", "/v2/vals", {"name": NAME, "privacy": "public",
        "description": "Mock Penn patient-access backend + ops console for a Bland pathway demo"})
    print("created val:", val.get("id"), val.get("_body", ""))
vid = val["id"]

# Embed the dashboard as modules so the val serves it without file reads.
# Val Town caps a file at 80K characters, so the page is split into parts that ui.ts joins.
html = (BACKEND / "dashboard.html").read_text()
parts = [html[i:i + 50000] for i in range(0, len(html), 50000)]
for old in BACKEND.glob("ui_part*.ts"):
    old.unlink()
for i, chunk in enumerate(parts):
    (BACKEND / f"ui_part{i}.ts").write_text(f"// Generated by deploy.py from dashboard.html.\nexport default {json.dumps(chunk)};\n")
(BACKEND / "ui.ts").write_text("// Generated by deploy.py from dashboard.html. Edit dashboard.html instead.\n"
    + "".join(f'import p{i} from "./ui_part{i}.ts";\n' for i in range(len(parts)))
    + f"const html = {' + '.join(f'p{i}' for i in range(len(parts)))};\nexport const dashboardHtml = () => html;\n")


def upload(name, kind):
    q = "?" + urllib.parse.urlencode({"path": name})
    body = {"content": (BACKEND / name).read_text(), "type": kind}
    res = call("PUT", f"/v2/vals/{vid}/files{q}", body)
    if "_error" in res:
        res = call("POST", f"/v2/vals/{vid}/files{q}", body)
    if "_error" in res:
        raise SystemExit(f"{name}: {res}")
    return res


for f in ["logic.ts", "db.ts", "bland.ts", *[f"ui_part{i}.ts" for i in range(len(parts))], "ui.ts"]:
    upload(f, "script")
    print("uploaded", f)
res = upload("main.ts", "http")
print("uploaded main.ts")

# Environment variables (create, or update if they already exist).
want = {"BLAND_API_KEY": E.get("BLAND_API_KEY", ""), "ADMIN_TOKEN": E["ADMIN_TOKEN"],
        "PATHWAY_ID": (ROOT / ".pathway_id").read_text().strip() if (ROOT / ".pathway_id").exists() else "",
        "TRANSFER_NUMBER": E.get("TRANSFER_NUMBER", ""), "BLAND_WEBHOOK_SECRET": E.get("BLAND_WEBHOOK_SECRET", "")}
have = {v["key"] for v in call("GET", f"/v2/vals/{vid}/environment_variables").get("data", [])}
for k, v in want.items():
    if not v.strip():
        continue
    if k in have:
        r = call("PUT", f"/v2/vals/{vid}/environment_variables/{k}", {"value": v.strip()})
    else:
        r = call("POST", f"/v2/vals/{vid}/environment_variables", {"key": k, "value": v.strip()})
    print("env", k, "error " + str(r.get("_error")) + " " + r.get("_body", "") if "_error" in r else "ok")

endpoint = (res.get("links") or {}).get("endpoint")
if endpoint:
    (ROOT / ".backend_url").write_text(endpoint.rstrip("/"))
    print("endpoint:", endpoint)
